### ISSUE TITLE
Reserve Margin

### ISSUE THREAD

**Issue by PriyankaKushwaha940** [NREL/ReEDS-2.0#164]
Hi,

To calculate the reserve margin on a country or state level, which files (input/output) need to be considered for the data? The files that are close are mentioned along with each line item, please confirm the source
1. CF (capacity factors, ELCC, technology-wise, year on year) - **cfout**
2. Peak demand - **peakall**
3. Existing and added capacity - **cap_new_ann**, cap, cap_firm, cap_firm_iter (not sure which to consider)

Any file/source that can give a better picture like which input files and output files have what kind of information would be super helpful. 

Thanks

**Comment by wesleyjcole** [comment]
Would you mind moving this question to the discussions page (https://github.com/NREL/ReEDS-2.0/discussions)?  We would like to keep questions and discussion about model use separate from issues.

**Comment by PriyankaKushwaha940** [comment]
Sure, I was not aware of it.
