### ISSUE TITLE
A bit of broken code in /postprocessing/bokehpivot/reeds2.py

### ISSUE THREAD

**Issue by wshobe** [NREL/ReEDS-2.0#189]
### Description of Issue
Our new instantiation of the ReEDS 2.0 model failed to produce any reports. The reason appears to be the addition of two new lines of code in postprocessing/bokehpivot/reeds2.py. One of these lines has a hardcoded directory in it, causing the generation of output to fail:

> water_techs = pd.read_csv('/Users/jcarag/ReEDS/PSH_Updates/ReEDS-2.0/postprocessing/bokehpivot/in/reeds2/tech_ctt_wst.csv')['tech'].tolist()
> water_techs = [x.lower() for x in water_techs]
> 

### Potential Solutions

If this new water_techs code needs to be outside of the add_cooling_water function, then the first line (above) should probably read:

water_techs = pd.read_csv(this_directory_path + '/in/reeds2/tech_ctt_wst.csv')['tech'].tolist()

**Comment by pesap** [comment]
Hi @wshobe ,

Thanks for reporting the bug in the code! We also noticed this on the internal version and we are working on the fix as we speak. We will roll the fix on the next version.

cc @kennedy-mindermann

**Comment by kennedy-mindermann** [comment]
I just merged a PR (#190) with a fix for this issue.
