### ISSUE TITLE
Error with implementation of 'historic' switch in runbatch.py 

### ISSUE THREAD

**Issue by wshobe** [NREL/ReEDS-2.0#196]
### Description of Issue

We were unable to use the 'historic' setting of the GSw_EFS1_AllYearLoad switch. The use of the 'historic' setting caused an immediate failure due to an exception being raised: _"The demand file specified by the demandscen switch is not in the inputs/load folder"_ Essentially this was a 'file not found' error indicating that the file specified in the 'demandscen' field was not present.

### Potential Solutions

This problem is due to a coding error in the following code in runbatch.py (around line 342):
`        if ('demand_' + sw['demandscen'] +'.csv') in os.listdir(os.path.join(reeds_path, 'inputs','load')) :
                raise ValueError("The demand file specified by the demandscen switch is not in the inputs/load folder")
`
The logical test here should be 'not in' rather than 'in'. Missing the negation results in an exception whenever the required file is present; clearly the opposite of what is intended.

**Comment by kennedy-mindermann** [comment]
Thanks for finding this bug! I'll get a fix merged in soon.
